---
title: "Untitled"
runtime: shiny
output: ioslides_presentation
---

## Shiny Presentation

This R Markdown presentation is made interactive using Shiny. The viewers of the presentation can change the assumptions underlying what's presented and see the results immediately. 

To learn more, see [Interactive Documents](http://rmarkdown.rstudio.com/authoring_shiny.html).

## Slide with Interactive Plot

```{r, echo=FALSE,message=FALSE}
library(ggplot2)
library(dplyr)
library(tidyr)
library(shiny)
#load("/Volumes/PERSONAL/MS/vash+ash/dsc-poisthin-indep/res.Rdata")
res.indep = readRDS("/Volumes/PERSONAL/MS/vash+ash/dsc-poisthin-indep/res_indep.RDS")

res.indep = separate(res.indep,scenario,c("scenario","nsamp"),",")
res.indep$nsamp = factor(res.indep$nsamp, levels=c("nsamp=2","nsamp=10","nsamp=50"))
res.indep$scenario = factor(res.indep$scenario, levels=c("spiky","near_normal","flat_top",
                                             "skew","big-normal","bimodal"))

scenario_names = as.character(unique(res.indep$scenario))
nsamp_names = as.character(unique(res.indep$nsamp))
method_names = as.character(unique(res.indep$method))
numeric_criteria = names(res.indep)[unlist(lapply(res.indep,is.numeric))]

shinyApp(
  ui=fluidPage(
    tags$head(tags$style(HTML("
                              .selectize-input, .selectize-dropdown {
                              font-size: 75%;
                              }
                              "))),    
    sidebarLayout(
      sidebarPanel(   
        fluidRow(column(6,
                        checkboxGroupInput("scen.subset", "Scenarios", 
                                           choices  = scenario_names,
                                           selected = scenario_names),
                        
                        checkboxGroupInput("nsamp.subset", "Sample sizes", 
                                           choices  = nsamp_names,
                                           selected = nsamp_names),
                        
                        checkboxGroupInput("method.subset", "Methods", 
                                           choices  = method_names,
                                           selected = method_names),
                        
                        selectInput("criteria", "Criteria", 
                                    choices  = numeric_criteria,
                                    selected = "pi0.est")
                        
                        )),width=4
        ),
      # Show a plot of the generated distribution
      mainPanel(
        plotOutput("plot")       
        )
      )
    ),
  server = function(input, output) {
    output$plot <- renderPlot({
      input$newplot
      res.indep.filter = filter(res.indep,scenario %in% input$scen.subset & nsamp %in% input$nsamp.subset & method %in% input$method.subset)
      res.indep.filter$value = res.indep.filter[[input$criteria]]

p=ggplot(res.indep.filter, aes(pi0,value,colour=method))+
  facet_grid(nsamp~scenario) + geom_point(shape=16) +xlim(0,1) +ylim(0,1) + 
  xlab("true pi0")   +theme(legend.position="bottom") +coord_equal() 
if (input$criteria=="pi0.est"){
  p+ylab("estimated pi0")+geom_abline(slope=1,intercept=0,color=1)
}else if (input$criteria=="FDP_005"){
  p+ylab("false discovery proportion when q<0.05")+geom_abline(slope=0,intercept=0.05,color=1)
}else if (input$criteria=="DP_005"){
  p+ylab("discovery proportion when q<0.05")+geom_abline(slope=-1,intercept=1,color=1)
}else{
  p+ylab(input$criteria)
}

    })
  
  }
  )
```

## 2
```{r, echo=FALSE,message=FALSE}
library(ggplot2)
library(dplyr)
library(tidyr)
library(shiny)
#load("/Volumes/PERSONAL/MS/vash+ash/dsc-poisthin-indep/res.Rdata")
res.dep = readRDS("/Volumes/PERSONAL/MS/vash+ash/dsc-poisthin-dep/res_dep.RDS")

res.dep = separate(res.dep,scenario,c("scenario","nsamp"),",")
res.dep$nsamp = factor(res.dep$nsamp, levels=c("nsamp=2","nsamp=10","nsamp=50"))
res.dep$scenario = factor(res.dep$scenario, levels=c("spiky","near_normal","flat_top",
                                             "skew","big-normal","bimodal"))

scenario_names = as.character(unique(res.dep$scenario))
nsamp_names = as.character(unique(res.dep$nsamp))
method_names = as.character(unique(res.dep$method))
numeric_criteria = names(res.dep)[unlist(lapply(res.dep,is.numeric))]

shinyApp(
  ui=fluidPage(
    tags$head(tags$style(HTML("
                              .selectize-input, .selectize-dropdown {
                              font-size: 75%;
                              }
                              "))),    
    sidebarLayout(
      sidebarPanel(   
        fluidRow(column(6,
                        checkboxGroupInput("scen.subset", "Scenarios", 
                                           choices  = scenario_names,
                                           selected = scenario_names),
                        
                        checkboxGroupInput("nsamp.subset", "Sample sizes", 
                                           choices  = nsamp_names,
                                           selected = nsamp_names),
                        
                        checkboxGroupInput("method.subset", "Methods", 
                                           choices  = method_names,
                                           selected = method_names),
                        
                        selectInput("criteria", "Criteria", 
                                    choices  = numeric_criteria,
                                    selected = "pi0.est")
                        
                        )),width=4
        ),
      # Show a plot of the generated distribution
      mainPanel(
        plotOutput("plot")       
        )
      )
    ),
  server = function(input, output) {
    output$plot <- renderPlot({
      input$newplot
      res.dep.filter = filter(res.dep,scenario %in% input$scen.subset & nsamp %in% input$nsamp.subset & method %in% input$method.subset)
      res.dep.filter$value = res.dep.filter[[input$criteria]]

p=ggplot(res.dep.filter, aes(pi0,value,colour=method))+
  facet_grid(nsamp~scenario) + geom_point(shape=16) +xlim(0,1) +ylim(0,1) + 
  xlab("true pi0")   +theme(legend.position="bottom") +coord_equal() 
if (input$criteria=="pi0.est"){
  p+ylab("estimated pi0")+geom_abline(slope=1,intercept=0,color=1)
}else if (input$criteria=="FDP_005"){
  p+ylab("false discovery proportion when q<0.05")+geom_abline(slope=0,intercept=0.05,color=1)
}else if (input$criteria=="DP_005"){
  p+ylab("discovery proportion when q<0.05")+geom_abline(slope=-1,intercept=1,color=1)
}else{
  p+ylab(input$criteria)
}

    })
  
  }
  )
```